return {
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = vim.fn.argc(-1) == 0,
		priority = 100,
		branch = "master",
		build = ":TSUpdate",
		opts = {
			ensure_installed = {
				"bash",
				"c",
				"cmake",
				"cpp",
				"diff",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitignore",
				"java",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"printf",
				"python",
				"regex",
				"rust",
				"vim",
				"vimdoc",
				"zig",
			},
			sync_install = false,
			auto_install = true,
			highlight = { enable = true, additional_vim_regex_highlighting = false },
			indent = { enable = true },
		},
	},
	{
		"nvim-treesitter/playground",
	},
}
